# Generated by Django 3.2.4 on 2025-02-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_new_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopmodel',
            name='link_subscription',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
