# Generated by Django 3.2.4 on 2025-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_new_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopmodel',
            name='link_subscription',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Insight URL'),
        ),
    ]
