# Generated by Django 3.2.4 on 2025-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0003_alter_laptopmodel_link_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopmodel',
            name='link_subsc',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Insight URL'),
        ),
    ]
