# Generated by Django 3.2.4 on 2025-03-28 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0007_alter_buttonchildmodel_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonchildmodel',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laptop.buttonmodel'),
        ),
    ]
