# Generated by Django 3.2.4 on 2025-03-28 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0009_alter_buttonchildmodel_b'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ButtonChildModel',
        ),
        migrations.DeleteModel(
            name='ButtonModel',
        ),
    ]
