# Generated by Django 3.2.4 on 2025-03-28 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0010_auto_20250328_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_child', to='laptop.bmodel')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laptop.bmodel')),
            ],
        ),
    ]
