# Generated by Django 3.2.4 on 2025-03-28 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0011_amodel_bmodel_cmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmodel',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laptop.bmodel'),
        ),
    ]
