# Generated by Django 3.2.4 on 2025-03-28 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0012_alter_cmodel_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmodel',
            name='a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_child', to='laptop.amodel'),
        ),
    ]
