# Generated by Django 3.2.4 on 2025-03-28 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0013_alter_cmodel_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmodel',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='laptop.bmodel'),
        ),
    ]
