# Generated by Django 3.2.4 on 2025-04-02 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0014_alter_cmodel_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 6, 29, 47, 548504)),
        ),
        migrations.AddField(
            model_name='cmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
