# Generated by Django 3.2.4 on 2025-04-02 09:09

import datetime
from django.db import migrations, models
# from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0015_auto_20250402_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmodel',
            name='a',
        ),
        migrations.RemoveField(
            model_name='cmodel',
            name='b',
        ),
        migrations.RemoveField(
            model_name='cmodel',
            name='modified',
        ),
        migrations.AddField(
            model_name='cmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 9, 9, 17, 975052,)),
        ),
    ]
