# Generated by Django 3.2.4 on 2025-04-02 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0016_auto_20250402_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 2, 9, 11, 59, 393325), null=True),
        ),
    ]
