# Generated by Django 5.1.4 on 2024-12-27 09:20

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flags', bitfield.models.BitField((('is_ram', 'ram is the user'), ('is_kane', 'kane is the user')), default=None)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
