# Generated by Django 5.1.4 on 2025-01-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_salesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
