# Generated by Django 5.1.4 on 2025-01-07 05:44

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_salesmodel_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='salesmodel',
            managers=[
                ('cus_man', django.db.models.manager.Manager()),
            ],
        ),
    ]
