# Generated by Django 3.2.4 on 2025-01-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userinfo_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
