# Generated by Django 3.2.4 on 2025-01-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
