# Generated by Django 3.2.4 on 2025-01-31 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_modela_modelb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelb',
            name='mo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_model', to='api.modela'),
        ),
    ]
