# Generated by Django 3.2.4 on 2025-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_timezonemodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ty', models.IntegerField(choices=[(2, 'Man'), (10, 'Woman')])),
            ],
        ),
    ]
