# Generated by Django 3.2.4 on 2025-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
