# Generated by Django 3.2.4 on 2025-02-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_post_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageFalseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
