# Generated by Django 3.2.4 on 2025-02-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_fileuploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
