# Generated by Django 3.2.4 on 2025-02-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_fileuploadmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
