# Generated by Django 3.2.4 on 2025-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_choicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicemodel',
            name='n',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=100),
        ),
    ]
