# Generated by Django 3.2.4 on 2025-03-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_changed_my_model0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicemodel',
            old_name='vv',
            new_name='vvv',
        ),
    ]
