# Generated by Django 3.2.4 on 2025-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_changed_my_model0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicemodel',
            name='n',
        ),
        migrations.RemoveField(
            model_name='choicemodel',
            name='vvv',
        ),
        migrations.AlterField(
            model_name='choicemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
