# Generated by Django 3.2.4 on 2025-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20250325_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tex', models.TextField()),
            ],
        ),
    ]
